apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - gvt
    environmentGitOwner: gvt
    gitKind: bitbucketserver
    gitName: bs
    gitServer: http://jxpoc.arubathena.com:7990
    provider: kubernetes
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: jxpoc.arubathena.com
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
